In [44]:
import pandas as pd

# A. POSITIONAL AND LABEL-BASED SLICING

**Complete list and shape of the name of all cars**

In [45]:
cars = pd.read_csv('cars.csv')
cars.loc[0:100,['Model']]

                  Model
0             Mazda RX4
1         Mazda RX4 Wag
2            Datsun 710
3        Hornet 4 Drive
4     Hornet Sportabout
5               Valiant
6            Duster 360
7             Merc 240D
8              Merc 230
9              Merc 280
10            Merc 280C
11           Merc 450SE
12           Merc 450SL
13          Merc 450SLC
14   Cadillac Fleetwood
15  Lincoln Continental
16    Chrysler Imperial
17             Fiat 128
18          Honda Civic
19       Toyota Corolla
20        Toyota Corona
21     Dodge Challenger
22          AMC Javelin
23           Camaro Z28
24     Pontiac Firebird
25            Fiat X1-9
26        Porsche 914-2
27         Lotus Europa
28       Ford Pantera L
29         Ferrari Dino
30        Maserati Bora
31           Volvo 142E

In [46]:
display(cars.loc[0:100,['Model']].shape)

(32, 1)

In [47]:
cars_6_to_10 = cars.iloc[5:10,[0,1,2,4,10]]

**cars_6_to_10  with Model, mpg, cyl, hp, and gear**

In [48]:
display(cars_6_to_10)

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

# B. MODEL LOOKUP

In [49]:
Toyota_Corolla = cars.loc[cars['Model']=='Toyota Corolla']
Pontiac_Firebird = cars.loc[(cars['Model']=='Pontiac Firebird'),['Model','mpg','hp','wt']]

**Toyota Corolla**

In [50]:
display(Toyota_Corolla)

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

**Pontiac Firebird**

In [51]:
display(Pontiac_Firebird)

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

# C. MULTI-MODEL SUBSETTING

In [52]:
selected_cars = pd.DataFrame(cars.loc[
    (cars['Model'] == 'Datsun 710') |
    (cars['Model'] == 'Lotus Europa') |
    (cars['Model'] == 'Ferrari Dino'),
    ['Model', 'mpg', 'cyl', 'hp', 'gear']])

**Datsun 710, Lotus Europa, Ferrari Dino with Model, mpg, cyl, hp, and gear with the shape**

In [53]:
display(selected_cars)

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

In [54]:
display(selected_cars.shape)

(3, 5)